services:
  - type: web
    name: drivefleet-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    rootDir: drivefleet-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: SERVER_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: COOKIE_NAME
        value: drivefleet_token
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
